### ISSUE TITLE
Please provide Qt Creator project files

### ISSUE THREAD

**Issue by sail2themoon** [shemeshg/RtMidiWrap#3]
Hi, I'm not able to compile this without Qt or/and Qt Creator. I've tried it with Qt alone, but it didn't find Qt6-config, even though I pointed to where it was.
Since you use Qt Creator as IDE, I'd try it with Qt Creator, but there aren't any informations about the compiler settings.. Could you please provide the necessary project files to open your project in Qt Creator?

Kind regards,
Simon

**Comment by shemeshg** [comment]
Hi

You are right, I have fixed the readme, in did were misleading..

it is using the latest qt6 with QtWebChannels (Qt6 LTS would be fine also) .
So better  install complete Qt from the Qt web site to insure you have QtWebChannels.
 ( Qt used also for Signal and Slots to coordinate the qtwebsockets with the RtMidi callback, and for server GUI QWidget), But all the rest is just standard c++


There are no other dependencies, so it should be really straight forward.
Once Qt installed completely (For example, linux Qt6 apt-get comes without QtWebChannels, and Mac's `homebrew` also) 

1. Delete previous compiler settings (CMakeLists.txt.user) and it will be recreated correctly
1.1 It had failed for me also after xcode upgrade (or windows update) so delete the .`CMakeLists.txt.user` and `build folder`  and start again.
2. Delete the "/build-" folder
3. File open the `https://github.com/shemeshg/RtMidiWrap/blob/master/CMakeLists.txt` from qtCreator
4.  select compile.

1.
![image](https://user-images.githubusercontent.com/8200598/208305644-d401a107-daac-48d4-8cfe-a3a6cf8ed6c4.png)

2.
![image](https://user-images.githubusercontent.com/8200598/208305673-96484ef5-1823-47a3-9a0d-2d8a08e13def.png)

3.
Cmd+B

And you'll see all ok
```
17:06:47: Running steps for project RtMidiRoute...
17:06:47: Starting: "/usr/local/Cellar/cmake/3.25.1/bin/cmake" --build /Volumes/FAST/develop/MidiRouter/projects/build-RtMidiWrap-Qt_6_4_0_for_macOS-Debug --target all
...
...
```

* I can provide my `CMakeLists.txt.user` but it is good only for Mac, with the specific XCODE version, so it is better to 
delete that file , and let it identify that automatically.

If you still have problems provide the compile output log

![image](https://user-images.githubusercontent.com/8200598/208305984-547b1be8-8c93-4d92-b2da-52bfa0b9564a.png)

**Comment by sail2themoon** [comment]
Thank you very much for your detailed answer. I'm using Qt Creator 9.0.1 from qt.io, and compiled by myself qt-everywhere-src-6.4.1 on Linux. I've added qmake from my built in the IDE, but got errors on compile: "RtMidiWrap.h:70: error ‘unique_ptr’ in namespace ‘std’ does not name a template type" - I've found a solution that fixes the error, just by adding "#include <memory>" on the top of RtMidiWrap.h.

**Comment by shemeshg** [comment]
Don't add QMAKE, I've already migrated from QMAKE to CMAKE and the CMAKE is fine.
I should have deleted the '[MidiRouter.pro.backup](https://github.com/shemeshg/RtMidiWrap/blob/master/MidiRouter.pro.backup)' from this repository long ago...
So, don't use that QMAKE file.

1. The error indicates  the gcc is on 'cpp11' and not 17.
2. So in your qmake you'll have to say something equivalent to  `set(CMAKE_CXX_STANDARD 17)`
But don't use qmake 
Use CMAKE
3. Using Qmake and not cmake you will have to do the `add_subfolder` equivalent also.
But don't use qmake 
Use CMAKE

I had some problems on Ubuntu 18.04 before because gcc was too old.
However it seems you are on Ubuntu20.04 so this is not the issue....
Also Qt6 LTS probably work on ubuntu18.04 also

On ubuntu 20.04 I have used the installer from QT 
https://www.qt.io/download-thank-you?os=linux&hsLang=en
And everything was ok automatically straight forward....

the `cmaklists.txt already have `set(CMAKE_CXX_STANDARD 17)` so opening this cmake file
should propagate to the RtMidi sub_folder (File->open file or project->select cmakelists.txt)

* If you start by installing the https://www.qt.io/download-thank-you?os=linux&hsLang=en
and see it all work, you can always select from the QT creator the qt-everywhere-src-6.4.1 and test with that later,
Or event temporary rename the Qt folder with the https://www.qt.io/download-thank-you?os=linux&hsLang=en to ensure the OS package `qt-everywhere-src-6.4.1`  is sufficient (Or not)

**Comment by shemeshg** [comment]
Actually I think Adding this include you've found is actually the right thing.....
It is very common that linux requires standard includes windows and mac don't
And it can't do harm
* What include was it?
* Anyway, dont use the QMAKE file, use the cmake
* So as I understand qt-everywhere-src-6.4.1 **is** sufficient

Thanks
Shemeshg

**Comment by sail2themoon** [comment]
sorry, that was a typo: I mean, I've added "#include <memory>" (just as seen here, no .h) in RtMidiWrap.h.
I'll check that gcc version later..
Thank you.

**Comment by sail2themoon** [comment]
Somehow the editor here strips that out in normal text:
`#include <memory>`

**Comment by shemeshg** [comment]
Thanks, I'll add that when I have a chance to test - before next release.
(I need to re-setup my linux machine since downgraded to 18.04 and now it is useless)

I do recall that it is where unique pointer managed (only in linux).

So no need to PR that. 

- Unless you needs that for packaging and uploading  to some production, so post PR and I'll merge that...)
